### ISSUE TITLE
build failed after linked

### ISSUE THREAD

**Issue by JayricMok** [prscX/react-native-shine-button#1]
Thank for making this library. But after I link the library, I get this error when build

```
Dex: Error converting bytecode to dex:WithDexForDebug
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
    UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
      at com.android.dx.command.dexer.Main.processClass(Main.java:752)
       at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
   at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
 at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
   at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
       at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
  at com.android.dx.command.dexer.Main.processOne(Main.java:672)
 at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
 at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
       at com.android.dx.command.Main.main(Main.java:106)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
   at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
   at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
     at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
 at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
 at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
 at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
      at com.android.dx.command.dexer.Main.processClass(Main.java:749)
       ... 12 more

1 error; aborting
:app:transformClassesWithDexForDebug FAILED
```

**Comment by prscX** [comment]
Thanks @JayricMok for raising the issue.

I have changed the `build:gradle:1.3.1` to `gradle:2.2.3`, hope it should fix the raised issue. Can you please download latest v0.0.4 and verify the same.

Please let know in case it does not work. If it does not work can you please verify the same by adding below snippet into library `build.gradle` file:

```
dexOptions {
  incremental true
}

compileOptions {
  sourceCompatibility JavaVersion.VERSION_1_8
  targetCompatibility JavaVersion.VERSION_1_8
}
```

Reference: [android-dex-cannot-parse-version-52-byte-code](https://stackoverflow.com/questions/37020413/android-dex-cannot-parse-version-52-byte-code)

Thanks
Pranav

**Comment by prscX** [comment]
Hi @JayricMok, I believe you have fixed the issue. If yes can you please share the solution with us.

Thanks
</ Pranav >

**Comment by joefazz** [comment]
Hello, this issue still exists in 0.0.5, I tried making the change you recommended above but still not building.

**Comment by prscX** [comment]
Hi @joefazz + @JayricMok,

Can you please add below snippet to `defaultConfig` in app `build.gradle` file in order to solution the issue:

```
jackOptions {
    enabled true
}
```

I have specified the same in `README` as well. Please let me know in case it does not work.

Thanks
</ Pranav >
